import type { MenuType } from "../types";
import {
  Banknote,
  CalendarSync,
  Home as HomeLucideIcon,
  Landmark,
  Layers2,
  Wallet,
  ShoppingCart,
  Train,
  Tv,
  UtensilsCrossed,
  HeartPulse,
  Coffee,
  ShoppingBag,
  TrendingUp,
  Zap,
  Home,
  Plane,
  BookOpen,
  Dumbbell,
  Gift,
  Car,
  Wifi,
} from "lucide-react";

export const MENU: MenuType[] = [
  { title: "Home", Icon: HomeLucideIcon, link: "/home" },
  { title: "Transaction", Icon: Banknote, link: "/transaction" },
  { title: "Category", Icon: Layers2, link: "/category" },
  { title: "Budget", Icon: Wallet, link: "/budget" },
  { title: "Subscriptions", Icon: CalendarSync, link: "/subscription" },
  { title: "Accounts", Icon: Landmark, link: "/account" },
];

export const CURRENCY = ["¥", "$", "€"];

export const MOCK_DATA = {
  CATEGORY: [
    {
      title: "Grocery",
      Icon: ShoppingCart,
      numberOfTransaction: 0,
      type: "Expense",
    },
    {
      title: "Transport",
      Icon: Train,
      numberOfTransaction: 0,
      type: "Expense",
    },
    {
      title: "Entertainment",
      Icon: Tv,
      numberOfTransaction: 0,
      type: "Expense",
    },
    {
      title: "Food",
      Icon: UtensilsCrossed,
      numberOfTransaction: 0,
      type: "Expense",
    },
    {
      title: "Health",
      Icon: HeartPulse,
      numberOfTransaction: 0,
      type: "Expense",
    },
    { title: "Dining", Icon: Coffee, numberOfTransaction: 0, type: "Expense" },
    {
      title: "Shopping",
      Icon: ShoppingBag,
      numberOfTransaction: 0,
      type: "Expense",
    },
    {
      title: "Income",
      Icon: TrendingUp,
      numberOfTransaction: 0,
      type: "Expense",
    },
    { title: "Utilities", Icon: Zap, numberOfTransaction: 0, type: "Expense" },
    { title: "Rent", Icon: Home, numberOfTransaction: 0, type: "Expense" },
    { title: "Travel", Icon: Plane, numberOfTransaction: 0, type: "Expense" },
    {
      title: "Education",
      Icon: BookOpen,
      numberOfTransaction: 0,
      type: "Expense",
    },
    { title: "Gym", Icon: Dumbbell, numberOfTransaction: 0, type: "Expense" },
    { title: "Gifts", Icon: Gift, numberOfTransaction: 0, type: "Expense" },
    { title: "Snacks", Icon: Coffee, numberOfTransaction: 0, type: "Expense" },
    { title: "Fuel", Icon: Car, numberOfTransaction: 0, type: "Expense" },
    { title: "Internet", Icon: Wifi, numberOfTransaction: 0, type: "Expense" },
    { title: "Wallet", Icon: Wallet, numberOfTransaction: 0, type: "Expense" },
  ],
  ACCOUNT: [
    {
      title: "MUFG Bank",
      balance: 280000,
      currency: "¥",
      totalTransaction: 12,
      type: "Bank",
    },
    {
      title: "Cash",
      balance: 15000,
      currency: "¥",
      totalTransaction: 5,
      type: "Cash",
    },
    {
      title: "Suica",
      balance: 3200,
      currency: "¥",
      totalTransaction: 8,
      type: "IC Card",
    },
    {
      title: "PayPay",
      balance: 8500,
      currency: "¥",
      totalTransaction: 15,
      type: "E-Wallet",
    },
    {
      title: "Rakuten",
      balance: 52000,
      currency: "¥",
      totalTransaction: 7,
      type: "E-Wallet",
    },
    {
      title: "7-Eleven ATM",
      balance: 20000,
      currency: "¥",
      totalTransaction: 3,
      type: "Cash",
    },
  ],
  BUDGET: [
    { title: "Grocery", spendAmount: 7200, totalAmount: 15000, currency: "¥" },
    { title: "Transport", spendAmount: 3100, totalAmount: 5000, currency: "¥" },
    { title: "Dining", spendAmount: 9800, totalAmount: 8000, currency: "¥" },
    {
      title: "Utilities",
      spendAmount: 4500,
      totalAmount: 10000,
      currency: "¥",
    },
    { title: "Health", spendAmount: 7000, totalAmount: 10000, currency: "¥" },
    {
      title: "Shopping",
      spendAmount: 12000,
      totalAmount: 20000,
      currency: "¥",
    },
    {
      title: "Entertainment",
      spendAmount: 2800,
      totalAmount: 5000,
      currency: "¥",
    },
  ],
  TRANSACTION: [
    {
      title: "FamilyMart",
      category: [
        { title: "Grocery", isMain: true },
        { title: "Snacks", isMain: false },
      ],
      note: "Morning coffee and onigiri",
      amount: -680,
      datetime: new Date(),
    },
    {
      title: "Suica Recharge",
      category: [{ title: "Transport", isMain: true }],
      note: "Monthly top-up",
      amount: -3000,
      datetime: new Date(),
    },
    {
      title: "Salary — March",
      category: [{ title: "Income", isMain: true }],
      note: "Monthly salary deposit",
      amount: 280000,
      datetime: new Date(),
    },
    {
      title: "Sukiya",
      category: [
        { title: "Dining", isMain: true },
        { title: "Lunch", isMain: false },
      ],
      note: "Gyudon set",
      amount: -490,
      datetime: new Date(Date.now() - 1000 * 60 * 60 * 3),
    },
    {
      title: "Amazon JP",
      category: [{ title: "Shopping", isMain: true }],
      note: "USB-C cable",
      amount: -1280,
      datetime: new Date("2026-03-17"),
    },
    {
      title: "Electricity Bill",
      category: [{ title: "Utilities", isMain: true }],
      note: "February billing cycle",
      amount: -4500,
      datetime: new Date("2026-03-17"),
    },
    {
      title: "Netflix",
      category: [{ title: "Entertainment", isMain: true }],
      note: "Monthly subscription",
      amount: -1490,
      datetime: new Date("2026-03-17"),
    },
    {
      title: "Lawson",
      category: [
        { title: "Grocery", isMain: true },
        { title: "Snacks", isMain: false },
      ],
      note: "Late night snacks",
      amount: -430,
      datetime: new Date("2026-03-16"),
    },
    {
      title: "Freelance Payment",
      category: [{ title: "Income", isMain: true }],
      note: "Logo design project",
      amount: 35000,
      datetime: new Date("2026-03-16"),
    },
    {
      title: "Uniqlo",
      category: [{ title: "Shopping", isMain: true }],
      note: "Spring jacket",
      amount: -5990,
      datetime: new Date("2026-03-16"),
    },
    {
      title: "Shinjuku Gym",
      category: [{ title: "Health", isMain: true }],
      note: "Monthly membership",
      amount: -7000,
      datetime: new Date("2026-03-15"),
    },
    {
      title: "Ramen Ichiran",
      category: [
        { title: "Dining", isMain: true },
        { title: "Dinner", isMain: false },
      ],
      note: "Solo dinner, extra chashu",
      amount: -1200,
      datetime: new Date("2026-03-15"),
    },
    {
      title: "Docomo Bill",
      category: [{ title: "Utilities", isMain: true }],
      note: "Mobile plan",
      amount: -3278,
      datetime: new Date("2026-03-15"),
    },
    {
      title: "Matsuya",
      category: [
        { title: "Dining", isMain: true },
        { title: "Breakfast", isMain: false },
      ],
      note: "Morning teishoku",
      amount: -380,
      datetime: new Date("2026-03-14"),
    },
    {
      title: "Book Off",
      category: [{ title: "Shopping", isMain: true }],
      note: "Used manga volumes",
      amount: -1500,
      datetime: new Date("2026-03-14"),
    },
    {
      title: "Sold — Old Laptop",
      category: [{ title: "Income", isMain: true }],
      note: "Mercari sale",
      amount: 18000,
      datetime: new Date("2026-03-14"),
    },
    {
      title: "Welcia Pharmacy",
      category: [
        { title: "Health", isMain: true },
        { title: "Grocery", isMain: false },
      ],
      note: "Cold medicine + vitamins",
      amount: -2340,
      datetime: new Date("2026-03-13"),
    },
    {
      title: "JR Pass",
      category: [{ title: "Transport", isMain: true }],
      note: "Weekend trip to Kamakura",
      amount: -1520,
      datetime: new Date("2026-03-13"),
    },
    {
      title: "Spotify",
      category: [{ title: "Entertainment", isMain: true }],
      note: "Monthly subscription",
      amount: -980,
      datetime: new Date("2026-03-12"),
    },
    {
      title: "7-Eleven",
      category: [
        { title: "Grocery", isMain: true },
        { title: "Snacks", isMain: false },
      ],
      note: "ATM + coffee",
      amount: -340,
      datetime: new Date("2026-03-12"),
    },
  ],
  SUBSCRIPTION: [
    {
      id: "sub-1",
      name: "Netflix",
      repeatNumber: 1,
      repeatUnit: "month",
      amount: 15,
      untilDate: new Date(2030, 1, 1),
      upcomingPayDate: new Date(2026, 2, 19),
      icon: ShoppingBag,
    },
    {
      id: "sub-2",
      name: "Spotify",
      repeatNumber: 1,
      repeatUnit: "year",
      amount: 99,
      untilDate: new Date(2030, 1, 1),
      upcomingPayDate: new Date(2026, 2, 20, 23, 59, 59),
      icon: ShoppingBag,
    },
    {
      id: "sub-3",
      name: "Gym",
      repeatNumber: 1,
      repeatUnit: "week",
      amount: 12,
      untilDate: new Date(2030, 1, 1),
      upcomingPayDate: new Date(2026, 2, 18, 23, 59, 59),
      icon: ShoppingBag,
    },
    {
      id: "sub-4",
      name: "Coffee App",
      repeatNumber: 1,
      repeatUnit: "day",
      amount: 3,
      untilDate: new Date(2030, 1, 1),
      upcomingPayDate: new Date(2026, 2, 19, 23, 59, 59),
      icon: ShoppingBag,
    },
    {
      id: "sub-5",
      name: "AWS",
      repeatNumber: 1,
      repeatUnit: "month",
      amount: 120,
      untilDate: new Date(2030, 1, 1),
      upcomingPayDate: new Date(2026, 3, 1, 23, 59, 59),
      icon: ShoppingBag,
    },
    {
      id: "sub-6",
      name: "Adobe",
      repeatNumber: 1,
      repeatUnit: "year",
      amount: 600,
      untilDate: new Date(2030, 1, 1),
      upcomingPayDate: new Date(2026, 5, 15, 23, 59, 59),
      icon: ShoppingBag,
    },
  ],
};
